### ISSUE TITLE
rails 7 +   caffeinate-webui  issue

### ISSUE THREAD

**Issue by nmaisonneuve** [joshmn/caffeinate-webui#1]
(@joshmn I open the issue here , more appropriate than the demo app github)

I added  caffeinate_webui + caffeinate on gemfile on rails 7 .
I also add "mount Caffeinate::Webui => '/campaigns_ui' " on my route. 

but when I launch the app  

1. I got a warning (related to zeitwerk)
..
WARNING: The following directories will only be checked if you configure
them to be eager loaded:

  /Users/x/.rvm/gems/ruby-3.2.1/gems/caffeinate_webui-0.1.0/lib/
  /Users/x/.rvm/gems/ruby-3.2.1/gems/caffeinate_webui-0.1.0/lib/caffeinate/
  /Users/x/.rvm/gems/ruby-3.2.1/gems/caffeinate_webui-0.1.0/lib/caffeinate/webui/
  
You may verify them manually, or add them to config.eager_load_paths in config/application.rb and run zeitwerk:check again.
..

2. then I got an error 

rails aborted!
ArgumentError: A rack application must be specified
/Users/x/dev/cityscoring/app_cityscoring/config/routes/admin.rb:8:in `block in draw'
...

Any help appreciated @joshmn?
(is this gem tested on Rails 7 ? Is this gem loaded in a particular manner ?)

**Comment by nmaisonneuve** [comment]
"Keep in mind, it's usually not a good idea to add paths from the gem directory directly to your Rails application's configuration. It's better to have the gem itself properly configure its own paths so that they are eager loaded by Zeitwerk. If possible, you may want to raise this issue with the maintainer of the caffeinate_webui gem."
from chatgpt :)

so in config/application.rb I added:

gem_path = Gem::Specification.find_by_name("caffeinate_webui").gem_dir
lib_path = gem_path + "/lib"

config.eager_load_paths << lib_path
config.eager_load_paths << lib_path + "/caffeinate"
config.eager_load_paths << lib_path + "/caffeinate/webui"

this removed the warning but I still got the error when I added 
mount Caffeinate::Webui => '/campaigns_ui'  

app_cityscoring-web-1      | /bundle/ruby/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:597:in `mount': A rack application must be specified (ArgumentError)
app_cityscoring-web-1      |
app_cityscoring-web-1      |           raise ArgumentError, "A rack application must be specified" unless app.respond_to?(:call)
app_cityscoring-web-1      |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app_cityscoring-web-1      | 	from /rails/config/routes/admin.rb:8:in `block in draw'
app_cityscoring-web-1      | 	from /bundle/ruby/3.2.0/gems/devise-4.9.2/lib/devise/rails/routes.rb:292:in `block in authenticate'
app_cityscoring-web-1      | 	from /bundle/ruby/3.2.0/gems/devise-4.9.2/lib/devise/rails/routes.rb:484:in `block in constraints_for'
app_cityscoring-web-1      | 	from /bundle/ruby/3.2.0/gems/actionpack-7.0.4.3/li


@joshmn  
Can you provide a rails 7 config example or upgrade your caffeinate demo app to rails 7 so we can see it ?

**Comment by nmaisonneuve** [comment]
@joshmn hi Josh ! do you have any news about this issue ?

**Comment by nmaisonneuve** [comment]
hi  @joshmn  can you confirm  this gem is rails 7 compatible ?

**Comment by erwin** [comment]
Running under Rails 7.0.4.3 I've been getting the same error as @nmaisonneuve when trying to test the caffeinate webui.

```
action_dispatch/routing/mapper.rb:597
in `mount': A rack application must be specified (ArgumentError)
```

<details>
<summary>Full backtrace:</summary>

```
=> Booting Puma
=> Rails 7.0.4.3 application starting in development
=> Run `bin/rails server --help` for more startup options
Exiting
/home/app/webapp/gems/ruby/3.1.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:597:in `mount': A rack application must be specified (ArgumentError)
        from /home/app/webapp/config/routes.rb:69:in `block (3 levels) in <main>'
        from /home/app/webapp/gems/ruby/3.1.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:871:in `scope'
        from /home/app/webapp/gems/ruby/3.1.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:1000:in `constraints'
        from /home/app/webapp/config/routes.rb:65:in `block (2 levels) in <main>'
        from /home/app/webapp/gems/ruby/3.1.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:871:in `scope'
        from /home/app/webapp/gems/ruby/3.1.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:940:in `block in namespace'
        from /home/app/webapp/gems/ruby/3.1.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:1862:in `path_scope'
        from /home/app/webapp/gems/ruby/3.1.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:939:in `namespace'
        from /home/app/webapp/gems/ruby/3.1.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:1572:in `namespace'
        from /home/app/webapp/config/routes.rb:64:in `block in <main>'
        from /home/app/webapp/gems/ruby/3.1.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/route_set.rb:428:in `instance_exec'
        from /home/app/webapp/gems/ruby/3.1.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/route_set.rb:428:in `eval_block'
        from /home/app/webapp/gems/ruby/3.1.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/route_set.rb:410:in `draw'
        from /home/app/webapp/config/routes.rb:1:in `<main>'
        from /home/app/webapp/gems/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/application/routes_reloader.rb:50:in `load'
        from /home/app/webapp/gems/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/application/routes_reloader.rb:50:in `block in load_paths'
        from /home/app/webapp/gems/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/application/routes_reloader.rb:50:in `each'
        from /home/app/webapp/gems/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/application/routes_reloader.rb:50:in `load_paths'
        from /home/app/webapp/gems/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/application/routes_reloader.rb:24:in `reload!'
        from /home/app/webapp/gems/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/application/routes_reloader.rb:38:in `block in updater'
        from /home/app/webapp/gems/ruby/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/file_update_checker.rb:83:in `execute'
        from /home/app/webapp/gems/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/application/routes_reloader.rb:13:in `execute'
        from /home/app/webapp/gems/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/application/finisher.rb:158:in `block in <module:Finisher>'
        from /home/app/webapp/gems/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:32:in `instance_exec'
        from /home/app/webapp/gems/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:32:in `run'
        from /home/app/webapp/gems/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
        from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/tsort.rb:347:in `each'
        from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/tsort.rb:347:in `call'
        from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
        from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
        from /home/app/webapp/gems/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:60:in `run_initializers'
        from /home/app/webapp/gems/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/application.rb:372:in `initialize!'
        from /home/app/webapp/config/environment.rb:5:in `<main>'
        from config.ru:3:in `require_relative'
        from config.ru:3:in `block in <main>'
        from /home/app/webapp/gems/ruby/3.1.0/gems/rack-2.2.6.4/lib/rack/builder.rb:116:in `eval'
        from /home/app/webapp/gems/ruby/3.1.0/gems/rack-2.2.6.4/lib/rack/builder.rb:116:in `new_from_string'
        from /home/app/webapp/gems/ruby/3.1.0/gems/rack-2.2.6.4/lib/rack/builder.rb:105:in `load_file'
        from /home/app/webapp/gems/ruby/3.1.0/gems/rack-2.2.6.4/lib/rack/builder.rb:66:in `parse_file'
        from /home/app/webapp/gems/ruby/3.1.0/gems/rack-2.2.6.4/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        from /home/app/webapp/gems/ruby/3.1.0/gems/rack-2.2.6.4/lib/rack/server.rb:249:in `app'
        from /home/app/webapp/gems/ruby/3.1.0/gems/rack-2.2.6.4/lib/rack/server.rb:422:in `wrapped_app'
        from /home/app/webapp/gems/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/commands/server/server_command.rb:76:in `log_to_stdout'
        from /home/app/webapp/gems/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/commands/server/server_command.rb:36:in `start'
        from /home/app/webapp/gems/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/commands/server/server_command.rb:143:in `block in perform'
        from <internal:kernel>:90:in `tap'
        from /home/app/webapp/gems/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/commands/server/server_command.rb:134:in `perform'
        from /home/app/webapp/gems/ruby/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /home/app/webapp/gems/ruby/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/app/webapp/gems/ruby/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /home/app/webapp/gems/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/command/base.rb:87:in `perform'
        from /home/app/webapp/gems/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/command.rb:48:in `invoke'
        from /home/app/webapp/gems/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/commands.rb:18:in `<main>'
        from /home/app/webapp/gems/ruby/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /home/app/webapp/gems/ruby/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from bin/rails:4:in `<main>'

```

</details>

The screenshots look great though!

**Comment by joshmn** [comment]
Ah, my friends, huge oversight in the readme:

```
mount Caffeinate::Webui::Engine => "/admin/caffeinate"
```

I've fixed this... :)

**Comment by erwin** [comment]
That fixed it. Thank you. The WebUI looks great!
